package com.example.gitagyan.screens.profile

object TheGreatnessOfTheGIta{
    const val englishTitle: String = "The Greatness of The Gita"
    const val englishContent: String = "Truly speaking, none has power to describe in words the glory of the Gita, for it is a book containing the highest esoteric doctrines. It is the essence of the Vedas; its language is so sweet and simple that man can easily understand it after a little practice; but the thoughts are so deep that none can arrive at their end even after constant study throughout a lifetime. Everyday they exhibit new facets of Truth, therefore they remain ever fresh and new. When scrutinized with a concentrated mind, possessed of faith and reverence, every verse of the Gita will clearly appear as full of the deepest mystery. The manner in which the Gita describes the virtues, glory and secrets of God, is hardly found in any other scripture; for in other books, the teachings are generally mixed up, more or less, with worldly subjects; but the Gita uttered by the Lord is such an incomparable book that not a word will be found in it, which is devoid of some spiritual import. That is why Shri Vedavyasa, after describing the Gita in the Mahabharata, said in the end - \n" +
            "\nगीता सुगीता कर्तव्या किमन्यैः शास्त्रविस्तरैः ।\n" +
            "या स्वंय पद्मनाभस्य मुखपद्माद्विनिः सृता ।।\n" +
            "\nThe Gita should be carefully studied, i.e., after reading the text, its meaning and idea should be gathered and held in the mind. It emanated from the lotus-like lips of Bhagavan Vishnu Himself, from whose navel sprung the lotus. What is the use of studying the other elaborate scriptures? Moreover, the Lord Himself also described its glory at the end of the Gita (Vide Chapter XVIII verses 68 to 71).\n" +
            "All men, irrespective of Varna and Ashrama, possess the right to study the Gita; the only qualifications needed are faith and reverence, for it is God's injunction to propagate the Gita only among His devotees, and He further said that women, Vaishyas, Shudras and even men born of sinful wombs can attain the supreme state of salvation, if they cultivate devotion to Him. And through worship of Him by the performance of their own nature-born duties, men can attain perfection (Chapter XVIII verse 46). Reflection on these verses make it clear that all men have equal right to God-realization.\n" +
            "But owing to lack of understanding of the truth behind this subject, many persons who have only heard the name of the Gita, make this assertion that the book is intended only for monks and ascetics, and they refrain from placing the book for study before their children out of fear lest through knowledge of the Gita the latter renounce their hearths and homes and turn ascetics themselves. But they should consider the fact that Arjuna, who had, due to infatuation, prepared himself to turn away from the duty of a Kshatriya and live on alms, being influenced by the most secret and mysterious teachings of the Gita, lived the life of a householder all his life and performed his duties; how can that very Gita produce this diametrically opposite result?\n" +
            "Therefore, men who desire their own welfare should give up this delusion and with utmost faith and reverence induce their children to study the Gita understanding the meaning and the underlying idea of every verse, and while studying and reflecting on it themselves, should, according to the injunction of the Lord, earnestly take to spiritual practice. For obtaining this most valuable human body, it is improper to waste even a single moment of one's time in indulging in transient enjoyments, the roots of sorrow."

    const val hindiTitle: String = "श्रीगीताजीकी महिमा"
    const val hindiContent: String = "वास्तवमें श्रीमद्भगवद्गीताका माहात्म्य वाणीद्वारा वर्णन करनेके लिये किसीकी भी सामर्थ्य नहीं है; क्योंकि यह एक परम रहस्यमय ग्रन्थ है । इसमें सम्पूर्ण वेदोंका सार-सार संग्रह किया गया है। इसकी संस्कृत इतनी सुन्दर और सरल है कि थोड़ा अभ्यास करनेसे मनुष्य उसको सहज ही समझ सकता है; परन्तु इसका आशय इतना गम्भीर है कि आजीवन निरन्तर अभ्यास करते रहनेपर भी उसका अन्त नहीं आता। प्रतिदिन नये-नये भाव उत्पन्न होते रहते हैं, इससे यह सदैव नवीन बना रहता है एवं एकाग्रचित्त होकर श्रद्धा-भक्तिसहित विचार करनेसे इसके पद-पदमें परम रहस्य भरा हुआ प्रत्यक्ष प्रतीत होता है। भगवान्\u200Cके गुण, प्रभाव और मर्मका वर्णन जिस प्रकार इस गीताशास्त्रमें किया गया है, वैसा अन्य ग्रन्थोंमें मिलना कठिन है; क्योंकि प्रायः ग्रन्थोंमें कुछ-न-कुछ सांसारिक विषय मिला रहता है। भगवान्\u200Cने 'श्रीमद्भगवद्गीता' रूप एक ऐसा अनुपमेय शास्त्र कहा है कि जिसमें एक भी शब्द सदुपदेशसे खाली नहीं है। श्रीवेदव्यासजीने महाभारतमें गीताजीका वर्णन करनेके उपरान्त कहा है-\n"+
            "\nगीता सुगीता कर्तव्या किमन्यैः शास्त्रविस्तरैः ।\n" +
            "या स्वंय पद्मनाभस्य मुखपद्माद्विनिः सृता ।।\n" +
            "\n'गीता सुगीता करनेयोग्य है अर्थात् श्रीगीताजीको भली प्रकार पढ़कर अर्थ और भावसहित अन्तःकरणमें धारण कर लेना मुख्य कर्तव्य है, जो कि स्वयं पद्मनाभ भगवान् श्रीविष्णुके मुखारविन्दसे निकली हुई है; (फिर) अन्य शास्त्रोंके विस्तारसे क्या प्रयोजन है ?' स्वयं श्रीभगवान्\u200Cने भी इसके माहात्म्यका वर्णन किया है (अध्याय १८ श्लोक ६८ से ७१ तक) ।\n"+
            "इस गीताशास्त्रमें मनुष्यमात्रका अधिकार है, चाहे वह किसी भी वर्ण, आश्रममें स्थित हो; परंतु भगवान्\u200Cमें श्रद्धालु और भक्तियुक्त अवश्य होना चाहिये; क्योंकि भगवान्\u200Cने अपने भक्तोंमें ही इसका प्रचार करनेके लिये आज्ञा दी है तथा यह भी कहा है कि स्त्री, वैश्य, शूद्र और पापयोनि भी मेरे परायण होकर परमगतिको प्राप्त होते हैं (अध्याय ९ श्लोक ३२ ); अपने-अपने स्वाभाविक कर्मोंद्वारा मेरी पूजा करके मनुष्य परम सिद्धिको प्राप्त होते हैं (अध्याय १८ श्लोक ४६ ) – इन सबपर विचार करनेसे यही ज्ञात होता है कि परमात्माकी प्राप्तिमें सभीका अधिकार है।\n"+
            "परन्तु उक्त विषयके मर्मको न समझनेके कारण बहुत-से मनुष्य, जिन्होंने श्रीगीताजीका केवल नाममात्र ही सुना है, कह दिया करते हैं कि गीता तो केवल संन्यासियोंके लिये ही है; वे अपने बालकोंको भी इसी भयसे श्रीगीताजीका अभ्यास नहीं कराते कि गीताके ज्ञानसे कदाचित् लड़का घर छोड़कर संन्यासी न हो जाय; किन्तु उनको विचार करना चाहिये कि मोहके कारण क्षात्रधर्मसे विमुख होकर भिक्षाके अन्नसे निर्वाह करनेके लिये तैयार हुए अर्जुनने जिस परम रहस्यमय गीताके उपदेशसे आजीवन गृहस्थमें रहकर अपने कर्तव्यका पालन किया, उस गीताशास्त्रका यह उलटा परिणाम किस प्रकार हो सकता है ?\n"+
            "अतएव कल्याणकी इच्छावाले मनुष्योंको उचित है कि मोहका त्यागकर अतिशय श्रद्धा-भक्तिपूर्वक अपने बालकोंको अर्थ और भावके सहित श्रीगीताजीका अध्ययन करायें एवं स्वयं भी इसका पठन और मनन करते हुए भगवान्\u200Cके आज्ञानुसार साधन करनेमें तत्पर हो जायँ; क्योंकि अति दुर्लभ मनुष्य-शरीरको प्राप्त होकर अपने अमूल्य समयका एक क्षण भी दुःखमूलक क्षणभंगुर भोगोंके भोगनेमें नष्ट करना उचित नहीं है।"


}
